// Automatically generated by the res2go IDE plug-in.
package main

import (
	"github.com/energye/golcl/inits"
	"github.com/energye/golcl/lcl"
)

func main() {
	inits.Init(nil, nil)
	lcl.Application.SetScaled(true)
	lcl.Application.SetTitle("project1")
	lcl.Application.Initialize()
	lcl.Application.SetMainFormOnTaskBar(true)
	lcl.Application.CreateForm(&Form1)
	lcl.Application.Run()
}
