// Automatically generated by the simple GoVCL IDE.
// 不要更改此文件名
// 在这里写你的事件。

package main

import (
	"github.com/energye/golcl/lcl"
)

//::private::
type TAppSettingsFields struct {
}

func (f *TAppSettings) OnFormCreate(sender lcl.IObject) {

}

func (f *TAppSettings) OnBtnSaveClick(sender lcl.IObject) {

}
