// Automatically generated by the simple Golcl IDE.
// 不要更改此文件名
// 在这里写你的事件。

package main

import (
	"github.com/energye/golcl/lcl/types"

	"github.com/energye/golcl/lcl"
)

//::private::
type TNewAliyunAudioEngineFields struct {
}

func (f *TNewAliyunAudioEngine) OnFormCreate(sender lcl.IObject) {

}

func (f *TNewAliyunAudioEngine) OnBtnOKClick(sender lcl.IObject) {
	if showNotAllowEmpty(f.EdtName, "名称/别名") {
		return
	}
	if showNotAllowEmpty(f.EdtAppKey, "AppKey") {
		return
	}

	if showNotAllowEmpty(f.EdtAccessKeyId, "AccessKeyId") {
		return
	}
	if showNotAllowEmpty(f.EdtAccessKeySecret, "AccessKeyId") {
		return
	}

	f.SetModalResult(types.MrOk)
}
