// Automatically generated by the simple Golcl IDE.
// 不要更改此文件名
// 在这里写你的事件。

package main

import (
	"github.com/energye/golcl/lcl"
	"github.com/energye/golcl/lcl/types"
)

//::private::
type TOSSSaveSettingsFields struct {
}

func (f *TOSSSaveSettings) OnFormCreate(sender lcl.IObject) {

}

func (f *TOSSSaveSettings) OnBtnSaveClick(sender lcl.IObject) {
	if showNotAllowEmpty(f.EdtEndPoint, "EndPoint") {
		return
	}
	if showNotAllowEmpty(f.EdtAccessKeyId, "AccessKeyId") {
		return
	}
	if showNotAllowEmpty(f.EdtAccessKeySecret, "AccessKeySecret") {
		return
	}
	if showNotAllowEmpty(f.EdtBucketName, "BucketName") {
		return
	}
	if showNotAllowEmpty(f.EdtBucketDomain, "BucketDomain") {
		return
	}

	f.SetModalResult(types.MrOk)
}
